name: ci

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make -C test CXX=${{ matrix.compiler }}
    - name: test
      run: cd test && ./test
